### ISSUE TITLE
Переименовать в "Эффективный Go"

### ISSUE THREAD

**Issue by egorsmkv** [Konstantin8105/Effective_Go_RU#4]
Предлагаю переименовать заголовок в "**Эффективный Go**".

> Эффективное программирование на языке Go

По-моему, всем и так ясно, что здесь идёт речь о *языке* Go, а написание кода предполагает *программирование* на Go. Уверен, что всем русскоговорящим название **Эффективный Go** будет понятно.

Кто за - ставьте палец вверх, кто против - вниз.

**Comment by Konstantin8105** [comment]
Спасибо за предложение.
Будет внесено
