### ISSUE TITLE
Использование термина "нулями"

### ISSUE THREAD

**Issue by egorsmkv** [Konstantin8105/Effective_Go_RU#5]
> К примеру ```new(T)``` резервирует память **нулями** для нового элемента типа ```T``` и возвращает его указатель на значение типа ```*T```. В терминологии Go, он возвращает указатель на новую зарезирвированную память заполненная **нулями** с типом ```T```.

Думаю, что это плохой термин и его нужно заменить. Для строкового типа ``string`` это будет пустое значение, а это никак не **нуль**.

Например:

- значение по-умолчанию

**Comment by Konstantin8105** [comment]
Со смыслом согласен. Проверю как в оригинале и исправлю

**Comment by Konstantin8105** [comment]
Из исходного документа:
"**...That is, new(T) allocates zeroed storage for a new item of type T and returns its address, a value of type *T. In Go terminology, it returns a pointer to a newly allocated zero value of type T...**"

**Comment by Konstantin8105** [comment]
Я так понимаю что значение по-умолчанию - нули, что подтверждается если создать переменные типа int, float... - изначальное значение нуль. Для строковой переменной нулевым является длина, а не значение.

**Comment by egorsmkv** [comment]
На деле там нули, но так выражаться, по-моему, не нужно. Там содержится **начальное значение**, **значение по-умолчанию**.

Можно выше дать определение этому понятию "значение по-умолчанию", где для числовых типов - нуль, для строки - пустая строка.

**Comment by romanyx** [comment]
Исходя из [спецификации](https://golang.org/ref/spec#The_zero_value) значение по-умолчанию и нулевое значение (для типа) используются как синонимы. Речь идет не о математическом нуле в буквальном смысле. В русском языке нулевое можно понять как пустое. Почему zero? Потому как zero все же подразумевает значение в отличии от null (от лат. nullus «никакой, ни один; несуществующий; пустой»).

**Comment by romanyx** [comment]
Таким образом, new(T) выделит память необходимую для хранения нового элемента типа T и вернет на нее адрес, значение с типом *T. Выражаясь терминологией Go, конструкция вернет указатель на память, выделенную под нулевое значение для типа T.
